const ecommerceProducts = {
    _id:{type:mongoose.ObjectId},
    manufacturerPartNo:{type:String},
    name:{type:String},
    description:{type:String},
    categoryId:[],
    unitPrice:{type:Number},
    MRP:{type:Number},
    images:[],
    note:{type:String},
    ranking:{type:Number},
    maxQuantityPerOrderNumber:{type:Number},
    sellerId:{type:String},
    _reviewAttributeId:{type:mongoose.ObjectId},
    status:{type:String},
    HSNCode:{type:String},
}