const ratingEntries = {
    _id:{type:mongoose.ObjectId},
    relType:{type:String},   
    _relId:{type:Smongoose.ObjectId},
    meta={
        [
            {
                _attributeId:{type:mongoose.ObjectId},
                type:{type:String},
                value:{type:String}
            }
        ]
    },
    _userId:{type:Smongoose.ObjectId}, 
    status:{type:String},   
    createdAt:{type:Date},
    createdBy:{type:mongoose.ObjectId},
    updatedBy:{type:mongoose.ObjectId}, 
    updatedAt:{type:Date}   
}